version: '3.5'

services:

  backend:
    build: ./server/
    env_file:
      - variables.env
    volumes:
      - ./server:/app      
    ports:
      - "5000:5000"
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: parla_net