version: '3.5'

services:    

  db:
    image: mongo:3.6.11
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-secret}    
    volumes:
      - mongo-db:/data/db      
      - ./data:/parlamentares    
    ports:
      - 27017:27017
    networks:
      - proxynet    

networks:
  proxynet:
    name: parla_net
    
volumes:
  mongo-db:  